export const Path = {
  Dashboard: '/',
  CompanyAssets: '/company-assets',
  Employee: {
    Dashboard: '/',
    ESS: {
      Leave: '/ess/leave-applications',
      LeaveNew: '/ess/leave-applications/new',
      LeaveType: '/ess/leave-applications/new?type=:type',
      OT: '/ess/ot-applications',
      OB: '/ess/ob-applications',
      OTNew: '/ess/ot-applications/new',
      WorkersOT: '/ess/workers-ot-applications',
    },
    Attendance: '/timekeeping',
    People: {
      Directory: '/people/directory',
      Departments: '/people/departments',
      Org: '/people/org-chart',
    },
    Announcements: '/announcements',
    Profile: '/profile',
  },
  Manager: {
    Dashboard: '/',
    Requests: {
      OT: '/manage/ot-applications',
      OB: '/manage/ob-applications',
      Leave: '/manage/leave-applications',
      WorkersOT: '/manage/workers-ot-applications',
    },
    People: {
      Directory: '/people/directory',
      Team: '/people/my-team',
    },
    Reports: '/reports',
    Announcements: '/announcements',
  },
  HR: {
    Dashboard: '/',
    Requests: {
      OT: '/requests/ot-applications',
      OB: '/requests/ob-applications',
      Leave: '/requests/leave-applications',
      WorkersOT: '/requests/workers-ot-applications',
    },
    People: {
      Directory: '/people/directory',
      Employees: '/people/employees',
      EmployeeProfile: '/profile/:employeeNo',
      Workers: '/people/workers',
      Departments: '/people/departments',
      Approvers: '/people/team-leaders',
      Org: '/people/org-chart',
    },
    Attendance: '/timekeeping',
    Reports: '/reports',
    Announcements: '/announcements',
  },
  Admin: {
    Dashboard: '/',
    Requests: {
      OB: '/requests/ob-applications',
      OT: '/requests/ot-applications',
      Leave: '/requests/leave-applications',
      WorkersOT: '/requests/workers-ot-applications',
    },
    People: {
      Directory: '/people/directory',
      Employees: '/people/employees',
      Workers: '/people/workers',
      Departments: '/people/departments',
      UserAccounts: '/people/user-accounts',
      Org: '/people/org-chart',
    },
    Attendance: '/timekeeping',
    Reports: {
      Audit: '/reports/audit',
      Tracker: '/reports/assets-tracker',
    },
    Automations: '/automations',
    Announcements: '/announcements',
    Company: {
      General: '/company/general',
      Positions: '/company/positions',
      Assets: '/company/assets',
    },
  },
};
