export const RELATION = ['PARENTS', 'SIBLINGS', 'SPOUSE', 'CHILDREN'];
export const USER_GROUP = ['HR ADMIN', 'SYSTEM ADMIN', 'APPROVER', 'EMPLOYEE'];
export const PAY_TYPE = ['BI MONTHLY', 'WEEKLY'];
export const PAYMENT_METHOD = ['CASH', 'CHECK', 'PAYROLL ACCOUNT'];
export const EMPLOYMENT_HISTORY_TYPE = "EMPLOYMENT",
    JOB_HISTORY_TYPE = "JOB",
    PERSONAL_HISTORY_TYPE = "PERSONAL";