/** USER ACCESS */
export const HR_ADMIN = 'HR ADMIN';
export const SYSAD = 'SYSTEM ADMIN';
export const MANAGER = 'APPROVER';
export const EMPLOYEE = 'EMPLOYEE';
/** USER ACCESS: END */

/** EMPLOYEE PROFILE CONFIGS */
export const RELATION = ['PARENTS', 'SIBLINGS', 'SPOUSE', 'CHILDREN'];
export const USER_GROUP = [HR_ADMIN, SYSAD, MANAGER, EMPLOYEE];
export const PAY_TYPE = ['BI MONTHLY', 'WEEKLY'];
export const PAYMENT_METHOD = ['CASH', 'CHECK', 'PAYROLL ACCOUNT'];
export const EMPLOYMENT_HISTORY_TYPE = "EMPLOYMENT",
    JOB_HISTORY_TYPE = "JOB",
    PERSONAL_HISTORY_TYPE = "PERSONAL";
export const ASSET_CONDITIONS = ["NEW", "USED", "DEFECTIVE", "TRANSFER"]
/** EMPLOYEE PROFILE CONFIGS: END */

/** REQUEST STATUS */
export const PENDING = "PENDING", APPROVED = "APPROVED", DISAPPROVED = "DISAPPROVED", CANCELLED = "CANCELLED";
export const REQUEST_STATUS = [PENDING, APPROVED, DISAPPROVED, CANCELLED]
/** REQUEST STATUS: END */

/** LEAVE CONFIGS */
export const ALLOWED_POST_FILING = ["EL", "SL"]
/** LEAVE CONFIGS: END */