import { EmployeeI } from 'slices/interfaces/employeeI';

export const initialState: EmployeeI = {
  employeeNo: '',
  firstName: '',
  lastName: '',
  middleName: '',
  suffix: '',
  citizenship: null,
  position: null,
  rank: null,
  department: null,
  location: [],
  isActive: true,
  userGroup: null,
  reportsTo: {
    employeeNo: "",
    employeeName: "",
    position: ""
  },
  dateHired: new Date(),
  employmentType: null,
  employmentStatus: null,
  endOfProbationary: null,
  contractEndDate: null,
  gender: null,
  birthDate: null,
  personalContactNumber: '',
  companyContactNumber: '',
  taxExemption: '',
  companyEmail: '',
  personalEmail: '',
  payrollBankAccount: {
    accountName: '',
    accountNumber: '',
    bankName: '',
    bankBranch: ''
  },
  civilStatus: null,
  religion: null,
  NumberOfDependents: undefined,
  sss: '',
  philHealth: '',
  pagIbig: '',
  tin: '',
  emergencyContact: [],
  govtProfExamsPassed: [],
  familyBackground: [],
  leave_requests: [],
  basicPay: 0.00,
  dateInactive: null,
  deductHMDF: 0.00,
  deductionSSS: 0.00,
  deductPhilhealth: null,
  deductWithholdingTax: 0.00,
  employeeBenefits: [],
  fixedContributionRate: null,
  paymentMethod: '',
  payRateType: null,
  payrollGroup: null,
  presentAddress: {
    addressLine: "",
    barangay: "",
    municipality: "",
    province: "",
    region: ""
  },
  permanentAddress: {
    addressLine: "",
    barangay: "",
    municipality: "",
    province: "",
    region: ""
  },
  educationalBackground: [],
  employmentRecords: [],
  licensesCertifications: [],
  allowanceDetails: [],
  yearsInService: 0,
  employment_history: [],
  employmentLastUpdate: undefined,
  jobLastUpdate: undefined,
  lastModifiedDate: undefined,
  dateCreated: undefined
};
